spring:
  driverClassName: 'org.h2.Driver'
  datasource:
    password: password
    username: sa
    url: 'jdbc:h2:mem:fornecedor'
  jpa:
    database-platform: 'org.hibernate.dialect.H2Dialect'
    hibernate:
      ddl-auto: update
